env:
  window_size: 10
  features: 5
  action_space: [sell, hold, buy]
  risk_agent: 1
  return_agent: 1
  trade_amount: 1000
  initial_balance: 1000000000.0
  reward_optimization: False

agent:
  learning_rate: 0.001
  epsilon_decay: 0.995
  epsilon_start: 0.9
  epsilon_end: 0.05
  gamma: 0.9

training:
  episodes: 100
  batch_size: 64
  replay_memory_size: 1000
  sample_size: 64
  target_update_frequency: 10
  dropout: 0.1
  seq_len: 10
  pred_len: 10
  label_len: 5
  patience: 7
  learning_rate: 0.001
  optimizer: "adam"
  target_update_frequency: 10
  discount_factor: 0.9
  model_save_dir: "./checkpoints"
  attention: False
  multi_stocks: False
  

data:
  ticker: "^DJI"
  ticker_list: ["AAPL", "MSFT", "GOOGL", "AMZN"]
  train_start_date: "2007-01-01"
  train_end_date: "2020-12-31"
  test_start_date: "2021-01-01"
  test_end_date: "2022-12-31"

timesnet:
  e_layers: 2
  checkpoints: "./checkpoints"
  dimension: 128
  input_dim: 5
  output_dim: 1
  num_class: 3
  top_k: 5
  enc_in: 5
  dec_in: 5
  num_kernels: 6
  patience: 7
  d_ff: 128
  d_model: 128
  output_attention: 1

mscnn:
  multi_scale:
    in_channels: 5
    out_channels: 64
  backbone:
    in_channels: 64
    out_channels: 64
  action:
    in_channel1: 8
    in_channel2: 8
    hidden_size: 64

gpu:
  use_gpu: 1

